# Generated by Django 4.1 on 2024-02-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=20)),
                ('seat', models.PositiveIntegerField()),
                ('vehicle_no', models.CharField(max_length=15)),
                ('transmission', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('deposit', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('id_card', models.CharField(max_length=200, verbose_name='idCard')),
                ('license_card', models.CharField(max_length=200, verbose_name='licenseCard')),
                ('phone_number', models.CharField(max_length=200, verbose_name='phoneNumber')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=100)),
                ('return_location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=15)),
                ('transport_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('damage_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.car')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trading_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_account_name', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='phoneNumber')),
                ('status', models.CharField(max_length=15, verbose_name='status')),
                ('balance', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('approved_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=6)),
                ('withdraw_datetime', models.DateTimeField()),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.provider')),
            ],
            options={
                'db_table': 'withdrawal',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.car')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.car')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customer')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('deposit_return_time', models.DateTimeField(blank=True, null=True)),
                ('refund_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.provider')),
            ],
            options={
                'db_table': 'chat_room',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('file_path', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('chat_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chatroom')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='CarFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=5)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.car')),
            ],
            options={
                'db_table': 'car_file',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.provider'),
        ),
    ]
