# Generated by Django 5.0.1 on 2024-02-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('idCard', models.CharField(max_length=200, verbose_name='idCard')),
                ('licenceCard', models.CharField(max_length=200, verbose_name='licenseCard')),
                ('phoneNumber', models.CharField(max_length=200, verbose_name='phoneNumber')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
        ),
    ]
