# Generated by Django 5.0.2 on 2024-02-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('seat', models.PositiveIntegerField()),
                ('vehicle_no', models.CharField(max_length=15)),
                ('trasmission', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('deposit', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=15)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trading_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_account_name', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20, verbose_name='phoneNumber')),
                ('status', models.CharField(max_length=15, verbose_name='status')),
                ('balance', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=5)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.provider'),
        ),
    ]
